import { Platform } from "react-native";
import normalize from "react-native-normalize";
import { Colors } from "./Colors";
import { StyleSheet } from "react-native";

export const AppStyles = {
  buttonTitle: {
    color: "white",
    fontSize: normalize(17),
    lineHeight: normalize(20.83),
    fontFamily: "Poppins-Semibold",
  },
  buttonOutline: {
    borderRadius: 50,
    paddingVertical: 1,
    paddingHorizontal: 1,
  },
  buttonContainer: {
    paddingVertical: 13,
    paddingHorizontal: 73,
    borderRadius: 50,
  },
  ////////////////////////////
  semibold40: {
    color: Colors.lightText,
    fontSize: normalize(40),
    lineHeight: normalize(49),
    fontFamily: "Poppins-Semibold",
  },
  semibold20: {
    color: Colors.lightText,
    fontSize: normalize(20),
    lineHeight: normalize(24.5),
    fontFamily: "Poppins-Semibold",
  },
  semibold17: {
    color: Colors.lightText,
    fontSize: normalize(17),
    lineHeight: normalize(21),
    fontFamily: "Poppins-SemiBold",
    marginBottom: normalize(5),
  },
  semibold22: {
    color: Colors.lightText,
    fontSize: normalize(22),
    lineHeight: normalize(27),
    fontFamily: "Poppins-SemiBold",
  },
  semibold25: {
    color: "white",
    fontSize: normalize(25),
    fontFamily: "Poppins-SemiBold",
  },
  medium70: {
    color: "white",
    fontSize: normalize(70),
    fontFamily: "Poppins-Medium",
  },
  medium13: {
    color: Colors.darkGray,
    fontSize: normalize(13),
    lineHeight: normalize(17),
    fontFamily: "Poppins-Medium",
  },
  medium15: {
    color: Colors.darkText,
    fontSize: normalize(15),
    lineHeight: normalize(18.2),
    fontFamily: "Poppins-Medium",
  },
  medium16: {
    color: Colors.lightText,
    fontSize: normalize(16),
    lineHeight: normalize(24),
    fontFamily: "Poppins-Medium",
    letterSpacing: 0.15,
  },
  medium17: {
    color: Colors.darkGray,
    fontSize: normalize(17),
    lineHeight: normalize(20.62),
    fontFamily: "Poppins-Medium",
  },
  medium22: {
    fontFamily: "Poppins-Medium",
    fontSize: normalize(22),
    lineHeight: normalize(33),
    color: Colors.someGray,
  },
  ////////////////////////////
  screenContainer: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 20,
    justifyContent: "flex-start",
  },
  loginForm: {
    alignItems: "center",
    width: "100%",
    marginTop: normalize(100),
  },
  loginTextInput: {
    flex: 1,
    paddingRight: 20,
    paddingVertical: 16,
  },
  textInput: {
    paddingRight: 20,
    paddingVertical: 16,
    marginBottom: normalize(18),
    paddingHorizontal: 20,
    width: "100%",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.darkText,
    borderRadius: 10,
  },
  loginInputContainer: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.darkText,
    borderRadius: 10,
  },
  profileInput: {
    paddingRight: 20,
    fontFamily: "Poppins-Medium",
    color: Colors.lightText,
    width: "100%",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.darkText,
    borderRadius: 10,
    marginTop: normalize(25),
    paddingVertical: normalize(12.81),
    fontSize: Platform.select({
      ios: normalize(18),
      android: normalize(21),
    }),
    lineHeight: Platform.select({
      ios: normalize(24),
      android: normalize(27),
    }),
  },
  profileRowContainer: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: normalize(25),
  },
  profileRowIcon: {
    width: normalize(20.62),
    height: normalize(20.62),
    justifyContent: "center",
  },
  toggleContainer: {
    height: normalize(20.62),
    justifyContent: "center",
    paddingLeft: normalize(50),
  },
  headerContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  headerRightIcon: {
    width: normalize(27),
    height: normalize(27),
    alignItems: "flex-end",
  },
  avatarContainer: {
    width: 161 + 6.54,
    height: 155 + 6.54,
    backgroundColor: Colors.darkGray,
    borderRadius: 206.67,
    borderWidth: 3.27,
    borderColor: Colors.black,
    justifyContent: "center",
    alignItems: "center",
  },
  avatar: {
    width: 161,
    height: 155,
    borderRadius: 206.67,
  },
  editImage: {
    position: "absolute",
    right: 12.2,
    bottom: -8.61,
  },
  splashContainer: {
    flex: 1,
    alignItems: "center",
  },
  progressBarContainer: {
    alignItems: "center",
    flex: 1,
    justifyContent: "flex-end",
  },
  progressBar: {
    height: normalize(6),
    width: normalize(200),
    borderRadius: normalize(32),
    backgroundColor: Colors.gray,
  },
  notFoundPlaceholder: {
    textAlign: "center",
    position: "absolute",
    alignSelf: "center",
  },
  listContainer: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 20,
    justifyContent: "flex-start",
    paddingHorizontal: 0,
  },
  contactItem: {
    flexDirection: "row",
    paddingVertical: normalize(18.44),
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
  },
  contactImageContainer: {
    width: normalize(60),
    height: normalize(60),
    borderRadius: normalize(30),
    marginRight: normalize(18.44),
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.darkGray,
  },
  contactImage: {
    width: normalize(60),
    height: normalize(60),
    borderRadius: normalize(30),
    backgroundColor: Colors.darkGray,
  },
  checkBoxContainer: {
    width: normalize(20),
    height: normalize(20),
    borderRadius: normalize(10),
    justifyContent: "center",
    alignItems: "center",
  },
  searchFieldContainer: {
    width: "100%",
    flexDirection: "row",
    backgroundColor: Colors.moreBlack,
    paddingRight: 15,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    marginTop: normalize(25),
  },
  searchField: {
    backgroundColor: Colors.moreBlack,
    flex: 1,
    paddingVertical: 11,
    borderRadius: 10,
    paddingLeft: 15,
  },
};
